###
GET localhost:8080/users/octocat
Content-Type: application/json
###
GET localhost:8080/users
Content-Type: application/json
###
GET localhost:8080/users/dupajasiaxyzcyce
Content-Type: application/json